// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing Collector object.
public struct Collector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// name of resource.
  public var name: Swift.String = Swift.String()

  /// Output only. Create time stamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update time stamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// User specified name of the Collector.
  public var displayName: Swift.String = Swift.String()

  /// User specified description of the Collector.
  public var description: Swift.String = Swift.String()

  /// Service Account email used to ingest data to this Collector.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. Store cloud storage bucket name (which is a guid) created with
  /// this Collector.
  public var bucket: Swift.String = Swift.String()

  /// User specified expected asset count.
  public var expectedAssetCount: Swift.Int64 = Swift.Int64()

  /// Output only. State of the Collector.
  public var state: Collector.State = Collector.State()

  /// Output only. Client version.
  public var clientVersion: Swift.String = Swift.String()

  /// Output only. Reference to MC Source Guest Os Scan.
  public var guestOsScan: GuestOsScan? = nil

  /// Output only. Reference to MC Source vsphere_scan.
  public var vsphereScan: VSphereScan? = nil

  /// How many days to collect data.
  public var collectionDays: Swift.Int32 = Swift.Int32()

  /// Uri for EULA (End User License Agreement) from customer.
  public var eulaUri: Swift.String = Swift.String()

  /// Initialize a new instance of `Collector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Collector().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// -- Using suggestion from API Linter Analyzer for nesting enum --
  /// -- https://linter.aip.dev/216/nesting --
  /// State of a Collector (server_side).
  /// States are used for internal purposes and named to keep
  /// convention of legacy product:
  /// https://cloud.google.com/migrate/stratozone/docs/about-stratoprobe.
  public enum State: Codable, Equatable, Sendable {
    /// Collector state is not recognized.
    case unspecified
    /// Collector started to create, but hasn't been completed MC source creation
    /// and db object creation.
    case initializing
    /// Collector has been created, MC source creation and db object creation
    /// completed.
    case readyToUse
    /// Collector client has been registered with client.
    case registered
    /// Collector client is actively scanning.
    case active
    /// Collector is not actively scanning.
    case paused
    /// Collector is starting background job for deletion.
    case deleting
    /// Collector completed all tasks for deletion.
    case decommissioned
    /// Collector is in error state.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .initializing: return 1
      case .readyToUse: return 2
      case .registered: return 3
      case .active: return 4
      case .paused: return 5
      case .deleting: return 6
      case .decommissioned: return 7
      case .error: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .initializing: return "STATE_INITIALIZING"
      case .readyToUse: return "STATE_READY_TO_USE"
      case .registered: return "STATE_REGISTERED"
      case .active: return "STATE_ACTIVE"
      case .paused: return "STATE_PAUSED"
      case .deleting: return "STATE_DELETING"
      case .decommissioned: return "STATE_DECOMMISSIONED"
      case .error: return "STATE_ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STATE_INITIALIZING": self = .initializing
      case "STATE_READY_TO_USE": self = .readyToUse
      case "STATE_REGISTERED": self = .registered
      case "STATE_ACTIVE": self = .active
      case "STATE_PAUSED": self = .paused
      case "STATE_DELETING": self = .deleting
      case "STATE_DECOMMISSIONED": self = .decommissioned
      case "STATE_ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .initializing
      case 2: self = .readyToUse
      case 3: self = .registered
      case 4: self = .active
      case 5: self = .paused
      case 6: self = .deleting
      case 7: self = .decommissioned
      case 8: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .initializing: return try container.encode(1)
      case .readyToUse: return try container.encode(2)
      case .registered: return try container.encode(3)
      case .active: return try container.encode(4)
      case .paused: return try container.encode(5)
      case .deleting: return try container.encode(6)
      case .decommissioned: return try container.encode(7)
      case .error: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.rapidmigrationassessment.v1.Collector"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
