// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources.
///
/// @Snippet(path: "RapidMigrationAssessmentQuickstart")
public class RapidMigrationAssessmentClient: Clients.RapidMigrationAssessmentProtocol {
  let inner: any Clients.RapidMigrationAssessmentStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `RapidMigrationAssessmentClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.RapidMigrationAssessmentStub =
      try Clients.RapidMigrationAssessmentTransport(options)
    inner = Clients.RapidMigrationAssessmentRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RapidMigrationAssessmentLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create a Collector to manage the on-prem appliance which collects
  /// information about Customer assets.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateCollector")
  public func createCollector(
    request: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCollector(request: request, options: options)
  }

  /// Create a Collector to manage the on-prem appliance which collects
  /// information about Customer assets.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateCollector")
  public func createCollector(
    withPolling: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Collector(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createCollector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates an Annotation
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateAnnotation")
  public func createAnnotation(
    request: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAnnotation(request: request, options: options)
  }

  /// Creates an Annotation
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateAnnotation")
  public func createAnnotation(
    withPolling: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Annotation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Annotation>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Annotation(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createAnnotation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Annotation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details of a single Annotation.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetAnnotation")
  public func getAnnotation(
    request: GetAnnotationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
    try await self.inner.getAnnotation(request: request, options: options)
  }

  /// Lists Collectors in a given project and location.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListCollectors")
  public func listCollectors(
    request: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse {
    try await self.inner.listCollectors(request: request, options: options)
  }

  /// Lists Collectors in a given project and location.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListCollectors")
  public func listCollectors(
    byItem: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Collector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCollectors(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetCollector")
  public func getCollector(
    request: GetCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
    try await self.inner.getCollector(request: request, options: options)
  }

  /// Updates the parameters of a single Collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_UpdateCollector")
  public func updateCollector(
    request: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCollector(request: request, options: options)
  }

  /// Updates the parameters of a single Collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_UpdateCollector")
  public func updateCollector(
    withPolling: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Collector(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateCollector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Collector - changes state of collector to "Deleting".
  /// Background jobs does final deletion through producer API.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_DeleteCollector")
  public func deleteCollector(
    request: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCollector(request: request, options: options)
  }

  /// Deletes a single Collector - changes state of collector to "Deleting".
  /// Background jobs does final deletion through producer API.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_DeleteCollector")
  public func deleteCollector(
    withPolling: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Collector(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteCollector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Resumes the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ResumeCollector")
  public func resumeCollector(
    request: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.resumeCollector(request: request, options: options)
  }

  /// Resumes the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ResumeCollector")
  public func resumeCollector(
    withPolling: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Collector(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.resumeCollector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Registers the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_RegisterCollector")
  public func registerCollector(
    request: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.registerCollector(request: request, options: options)
  }

  /// Registers the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_RegisterCollector")
  public func registerCollector(
    withPolling: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Collector(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.registerCollector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Pauses the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_PauseCollector")
  public func pauseCollector(
    request: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.pauseCollector(request: request, options: options)
  }

  /// Pauses the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_PauseCollector")
  public func pauseCollector(
    withPolling: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Collector(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.pauseCollector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "RapidMigrationAssessment_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RapidMigrationAssessmentClient`.
  ///
  /// To mock `RapidMigrationAssessmentClient` change your functions to receive
  /// `some RapidMigrationAssessmentProtocol` or `any RapidMigrationAssessmentProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RapidMigrationAssessmentProtocol {
    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollector(request: CreateCollectorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollector(withPolling: CreateCollectorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollector(
      parent: Swift.String,
      collector: Collector?,
      collectorId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotation(request: CreateAnnotationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotation(withPolling: CreateAnnotationRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Annotation>

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotation(
      parent: Swift.String,
      annotation: Annotation?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Annotation>

    /// See `RapidMigrationAssessmentClient.getAnnotation`.
    func getAnnotation(request: GetAnnotationRequest) async throws
      -> GoogleCloudRapidMigrationAssessmentV1.Annotation

    /// See `RapidMigrationAssessmentClient.getAnnotation`.
    func getAnnotation(
      name: Swift.String,
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation

    /// See `RapidMigrationAssessmentClient.listCollectors`.
    func listCollectors(request: ListCollectorsRequest) async throws
      -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse

    /// See `RapidMigrationAssessmentClient.listCollectors`.
    func listCollectors(
      byItem: ListCollectorsRequest
    ) throws -> any AsyncSequence<Collector, Swift.Error>

    /// See `RapidMigrationAssessmentClient.listCollectors`.
    func listCollectors(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Collector, Swift.Error>

    /// See `RapidMigrationAssessmentClient.getCollector`.
    func getCollector(request: GetCollectorRequest) async throws
      -> GoogleCloudRapidMigrationAssessmentV1.Collector

    /// See `RapidMigrationAssessmentClient.getCollector`.
    func getCollector(
      name: Swift.String,
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollector(request: UpdateCollectorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollector(withPolling: UpdateCollectorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollector(
      collector: Collector?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollector(request: DeleteCollectorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollector(withPolling: DeleteCollectorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollector(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollector(request: ResumeCollectorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollector(withPolling: ResumeCollectorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollector(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollector(request: RegisterCollectorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollector(withPolling: RegisterCollectorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollector(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollector(request: PauseCollectorRequest) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollector(withPolling: PauseCollectorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollector(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `RapidMigrationAssessmentClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `RapidMigrationAssessmentClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `RapidMigrationAssessmentClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `RapidMigrationAssessmentClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `RapidMigrationAssessmentClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `RapidMigrationAssessmentClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `RapidMigrationAssessmentClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `RapidMigrationAssessmentClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `RapidMigrationAssessmentClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollector(
      request: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollector(
      withPolling: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotation(
      request: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotation(
      withPolling: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Annotation>

    /// See `RapidMigrationAssessmentClient.getAnnotation`.
    func getAnnotation(
      request: GetAnnotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation

    /// See `RapidMigrationAssessmentClient.listCollectors`.
    func listCollectors(
      request: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse

    /// See `RapidMigrationAssessmentClient.listCollectors`.
    func listCollectors(
      byItem: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Collector, Swift.Error>

    /// See `RapidMigrationAssessmentClient.getCollector`.
    func getCollector(
      request: GetCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollector(
      request: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollector(
      withPolling: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollector(
      request: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollector(
      withPolling: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollector(
      request: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollector(
      withPolling: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollector(
      request: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollector(
      withPolling: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollector(
      request: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollector(
      withPolling: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `RapidMigrationAssessmentClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `RapidMigrationAssessmentClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `RapidMigrationAssessmentClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `RapidMigrationAssessmentClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `RapidMigrationAssessmentClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `RapidMigrationAssessmentClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.RapidMigrationAssessmentProtocol {
  public func createCollector(request: CreateCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCollector(request: request, options: .init())
  }

  public func createCollector(
    request: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCollector(withPolling: CreateCollectorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Collector>
  {
    try await self.createCollector(withPolling: withPolling, options: .init())
  }

  public func createCollector(
    withPolling: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCollector(
    parent: Swift.String,
    collector: Collector?,
    collectorId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let request = CreateCollectorRequest().with {
      $0.parent = parent
      $0.collector = collector
      $0.collectorId = collectorId
    }
    return try await self.createCollector(withPolling: request)
  }

  public func createAnnotation(request: CreateAnnotationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAnnotation(request: request, options: .init())
  }

  public func createAnnotation(
    request: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAnnotation(withPolling: CreateAnnotationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Annotation>
  {
    try await self.createAnnotation(withPolling: withPolling, options: .init())
  }

  public func createAnnotation(
    withPolling: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Annotation> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Annotation>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAnnotation(
    parent: Swift.String,
    annotation: Annotation?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Annotation> {
    let request = CreateAnnotationRequest().with {
      $0.parent = parent
      $0.annotation = annotation
    }
    return try await self.createAnnotation(withPolling: request)
  }

  public func getAnnotation(request: GetAnnotationRequest) async throws
    -> GoogleCloudRapidMigrationAssessmentV1.Annotation
  {
    try await self.getAnnotation(request: request, options: .init())
  }

  public func getAnnotation(
    request: GetAnnotationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAnnotation(
    name: Swift.String,
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
    let request = GetAnnotationRequest().with {
      $0.name = name
    }
    return try await self.getAnnotation(request: request)
  }

  public func listCollectors(request: ListCollectorsRequest) async throws
    -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse
  {
    try await self.listCollectors(request: request, options: .init())
  }

  public func listCollectors(
    request: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCollectors(
    byItem: ListCollectorsRequest
  ) throws -> any AsyncSequence<Collector, Swift.Error> {
    try self.listCollectors(byItem: byItem, options: .init())
  }

  public func listCollectors(
    byItem: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Collector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCollectors(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Collector, Swift.Error> {
    let request = ListCollectorsRequest().with {
      $0.parent = parent
    }
    return try self.listCollectors(byItem: request)
  }

  public func getCollector(request: GetCollectorRequest) async throws
    -> GoogleCloudRapidMigrationAssessmentV1.Collector
  {
    try await self.getCollector(request: request, options: .init())
  }

  public func getCollector(
    request: GetCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCollector(
    name: Swift.String,
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
    let request = GetCollectorRequest().with {
      $0.name = name
    }
    return try await self.getCollector(request: request)
  }

  public func updateCollector(request: UpdateCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCollector(request: request, options: .init())
  }

  public func updateCollector(
    request: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCollector(withPolling: UpdateCollectorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Collector>
  {
    try await self.updateCollector(withPolling: withPolling, options: .init())
  }

  public func updateCollector(
    withPolling: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCollector(
    collector: Collector?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let request = UpdateCollectorRequest().with {
      $0.collector = collector
      $0.updateMask = updateMask
    }
    return try await self.updateCollector(withPolling: request)
  }

  public func deleteCollector(request: DeleteCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCollector(request: request, options: .init())
  }

  public func deleteCollector(
    request: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCollector(withPolling: DeleteCollectorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Collector>
  {
    try await self.deleteCollector(withPolling: withPolling, options: .init())
  }

  public func deleteCollector(
    withPolling: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCollector(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let request = DeleteCollectorRequest().with {
      $0.name = name
    }
    return try await self.deleteCollector(withPolling: request)
  }

  public func resumeCollector(request: ResumeCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.resumeCollector(request: request, options: .init())
  }

  public func resumeCollector(
    request: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func resumeCollector(withPolling: ResumeCollectorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Collector>
  {
    try await self.resumeCollector(withPolling: withPolling, options: .init())
  }

  public func resumeCollector(
    withPolling: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func resumeCollector(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let request = ResumeCollectorRequest().with {
      $0.name = name
    }
    return try await self.resumeCollector(withPolling: request)
  }

  public func registerCollector(request: RegisterCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.registerCollector(request: request, options: .init())
  }

  public func registerCollector(
    request: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func registerCollector(withPolling: RegisterCollectorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Collector>
  {
    try await self.registerCollector(withPolling: withPolling, options: .init())
  }

  public func registerCollector(
    withPolling: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func registerCollector(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let request = RegisterCollectorRequest().with {
      $0.name = name
    }
    return try await self.registerCollector(withPolling: request)
  }

  public func pauseCollector(request: PauseCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.pauseCollector(request: request, options: .init())
  }

  public func pauseCollector(
    request: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func pauseCollector(withPolling: PauseCollectorRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Collector>
  {
    try await self.pauseCollector(withPolling: withPolling, options: .init())
  }

  public func pauseCollector(
    withPolling: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Collector>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func pauseCollector(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Collector> {
    let request = PauseCollectorRequest().with {
      $0.name = name
    }
    return try await self.pauseCollector(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
