// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class RapidMigrationAssessmentLogging: RapidMigrationAssessmentStub {
    let inner: any RapidMigrationAssessmentStub
    let logger: Logger

    public init(_ inner: any RapidMigrationAssessmentStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-rapidmigrationassessment-v1"
      logger[metadataKey: "gcp.client.service"] = "rapidmigrationassessment"
      logger[metadataKey: "gcp.experimental.swift.client"] = "RapidMigrationAssessment"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createCollector(
      request: CreateCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCollector",
        action: {
          (r: CreateCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCollector(request: r, options: o)
        })
    }

    public func createAnnotation(
      request: CreateAnnotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAnnotation",
        action: {
          (r: CreateAnnotationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAnnotation(request: r, options: o)
        })
    }

    public func getAnnotation(
      request: GetAnnotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAnnotation",
        action: {
          (r: GetAnnotationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRapidMigrationAssessmentV1.Annotation
          in
          return try await self.inner.getAnnotation(request: r, options: o)
        })
    }

    public func listCollectors(
      request: ListCollectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCollectors",
        action: {
          (r: ListCollectorsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse
          in
          return try await self.inner.listCollectors(request: r, options: o)
        })
    }

    public func getCollector(
      request: GetCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCollector",
        action: {
          (r: GetCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRapidMigrationAssessmentV1.Collector
          in
          return try await self.inner.getCollector(request: r, options: o)
        })
    }

    public func updateCollector(
      request: UpdateCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCollector",
        action: {
          (r: UpdateCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCollector(request: r, options: o)
        })
    }

    public func deleteCollector(
      request: DeleteCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCollector",
        action: {
          (r: DeleteCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCollector(request: r, options: o)
        })
    }

    public func resumeCollector(
      request: ResumeCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeCollector",
        action: {
          (r: ResumeCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resumeCollector(request: r, options: o)
        })
    }

    public func registerCollector(
      request: RegisterCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "registerCollector",
        action: {
          (r: RegisterCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.registerCollector(request: r, options: o)
        })
    }

    public func pauseCollector(
      request: PauseCollectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "pauseCollector",
        action: {
          (r: PauseCollectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.pauseCollector(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
