// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol RapidMigrationAssessmentStub: Sendable {
    func createCollector(
      request: CreateCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createAnnotation(
      request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getAnnotation(
      request: GetAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation

    func listCollectors(
      request: ListCollectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse

    func getCollector(
      request: GetCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector

    func updateCollector(
      request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCollector(
      request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resumeCollector(
      request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func registerCollector(
      request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func pauseCollector(
      request: PauseCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
