// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources.
///
/// @Snippet(path: "RapidMigrationAssessmentQuickstart")
public final class RapidMigrationAssessmentClient: Clients.RapidMigrationAssessmentProtocol,
  Sendable
{
  let inner: any Clients.RapidMigrationAssessmentStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `RapidMigrationAssessmentClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.RapidMigrationAssessmentStub =
      try Clients.RapidMigrationAssessmentTransport(options)
    inner = Clients.RapidMigrationAssessmentRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RapidMigrationAssessmentLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create a Collector to manage the on-prem appliance which collects
  /// information about Customer assets.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateCollector")
  public func createCollector(
    request: CreateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCollector(request: request, options: options)
  }

  /// Create a Collector to manage the on-prem appliance which collects
  /// information about Customer assets.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateCollector")
  public func createCollectorPollingUntilDone(
    request: CreateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collector>.State
      in
      return try op._extractStatus(Collector.self)
    }
    let rawOp = try await self.createCollector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates an Annotation
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateAnnotation")
  public func createAnnotation(
    request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAnnotation(request: request, options: options)
  }

  /// Creates an Annotation
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CreateAnnotation")
  public func createAnnotationPollingUntilDone(
    request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Annotation> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Annotation>.State
      in
      return try op._extractStatus(Annotation.self)
    }
    let rawOp = try await self.createAnnotation(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Annotation>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details of a single Annotation.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetAnnotation")
  public func getAnnotation(
    request: GetAnnotationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
    try await self.inner.getAnnotation(request: request, options: options)
  }

  /// Lists Collectors in a given project and location.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListCollectors")
  public func listCollectors(
    request: ListCollectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse {
    try await self.inner.listCollectors(request: request, options: options)
  }

  /// Gets details of a single Collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetCollector")
  public func getCollector(
    request: GetCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
    try await self.inner.getCollector(request: request, options: options)
  }

  /// Updates the parameters of a single Collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_UpdateCollector")
  public func updateCollector(
    request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCollector(request: request, options: options)
  }

  /// Updates the parameters of a single Collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_UpdateCollector")
  public func updateCollectorPollingUntilDone(
    request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collector>.State
      in
      return try op._extractStatus(Collector.self)
    }
    let rawOp = try await self.updateCollector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Collector - changes state of collector to "Deleting".
  /// Background jobs does final deletion through producer API.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_DeleteCollector")
  public func deleteCollector(
    request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCollector(request: request, options: options)
  }

  /// Deletes a single Collector - changes state of collector to "Deleting".
  /// Background jobs does final deletion through producer API.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_DeleteCollector")
  public func deleteCollectorPollingUntilDone(
    request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collector>.State
      in
      return try op._extractStatus(Collector.self)
    }
    let rawOp = try await self.deleteCollector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Resumes the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ResumeCollector")
  public func resumeCollector(
    request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.resumeCollector(request: request, options: options)
  }

  /// Resumes the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ResumeCollector")
  public func resumeCollectorPollingUntilDone(
    request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collector>.State
      in
      return try op._extractStatus(Collector.self)
    }
    let rawOp = try await self.resumeCollector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Registers the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_RegisterCollector")
  public func registerCollector(
    request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.registerCollector(request: request, options: options)
  }

  /// Registers the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_RegisterCollector")
  public func registerCollectorPollingUntilDone(
    request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collector>.State
      in
      return try op._extractStatus(Collector.self)
    }
    let rawOp = try await self.registerCollector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Pauses the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_PauseCollector")
  public func pauseCollector(
    request: PauseCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.pauseCollector(request: request, options: options)
  }

  /// Pauses the given collector.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_PauseCollector")
  public func pauseCollectorPollingUntilDone(
    request: PauseCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collector>.State
      in
      return try op._extractStatus(Collector.self)
    }
    let rawOp = try await self.pauseCollector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RapidMigrationAssessment_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RapidMigrationAssessment_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RapidMigrationAssessment_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RapidMigrationAssessmentClient`.
  ///
  /// To mock `RapidMigrationAssessmentClient` change your functions to receive
  /// `some RapidMigrationAssessmentProtocol` or `any RapidMigrationAssessmentProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RapidMigrationAssessmentProtocol: Sendable {
    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollectorPollingUntilDone(request: CreateCollectorRequest) async throws
      -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollectorPollingUntilDone(
      parent: Swift.String,
      collector: Collector?,
      collectorId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotationPollingUntilDone(request: CreateAnnotationRequest) async throws
      -> any GoogleGax.PollableOperation<Annotation>

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotationPollingUntilDone(
      parent: Swift.String,
      annotation: Annotation?,
    ) async throws -> any GoogleGax.PollableOperation<Annotation>

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollectorPollingUntilDone(request: UpdateCollectorRequest) async throws
      -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollectorPollingUntilDone(
      collector: Collector?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollectorPollingUntilDone(request: DeleteCollectorRequest) async throws
      -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollectorPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollectorPollingUntilDone(request: ResumeCollectorRequest) async throws
      -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollectorPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollectorPollingUntilDone(request: RegisterCollectorRequest) async throws
      -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollectorPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollectorPollingUntilDone(request: PauseCollectorRequest) async throws
      -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollectorPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollector(
      request: CreateCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.createCollector`.
    func createCollectorPollingUntilDone(
      request: CreateCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotation(
      request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.createAnnotation`.
    func createAnnotationPollingUntilDone(
      request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Annotation>

    /// See `RapidMigrationAssessmentClient.getAnnotation`.
    func getAnnotation(
      request: GetAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation

    /// See `RapidMigrationAssessmentClient.listCollectors`.
    func listCollectors(
      request: ListCollectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse

    /// See `RapidMigrationAssessmentClient.getCollector`.
    func getCollector(
      request: GetCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollector(
      request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.updateCollector`.
    func updateCollectorPollingUntilDone(
      request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollector(
      request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.deleteCollector`.
    func deleteCollectorPollingUntilDone(
      request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollector(
      request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.resumeCollector`.
    func resumeCollectorPollingUntilDone(
      request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollector(
      request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.registerCollector`.
    func registerCollectorPollingUntilDone(
      request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollector(
      request: PauseCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RapidMigrationAssessmentClient.pauseCollector`.
    func pauseCollectorPollingUntilDone(
      request: PauseCollectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collector>

    /// See `RapidMigrationAssessmentClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `RapidMigrationAssessmentClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `RapidMigrationAssessmentClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `RapidMigrationAssessmentClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `RapidMigrationAssessmentClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.RapidMigrationAssessmentProtocol {
  public func createCollector(request: CreateCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCollector(request: request, options: .init())
  }

  public func createCollector(
    request: CreateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createCollectorPollingUntilDone(request: CreateCollectorRequest) async throws
    -> any GoogleGax.PollableOperation<Collector>
  {
    try await self.createCollectorPollingUntilDone(request: request, options: .init())
  }

  public func createCollectorPollingUntilDone(
    request: CreateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCollectorPollingUntilDone(
    parent: Swift.String,
    collector: Collector?,
    collectorId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let request = CreateCollectorRequest().with {
      $0.parent = parent
      $0.collector = collector
      $0.collectorId = collectorId
    }
    return try await self.createCollectorPollingUntilDone(request: request)
  }

  public func createAnnotation(request: CreateAnnotationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAnnotation(request: request, options: .init())
  }

  public func createAnnotation(
    request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAnnotationPollingUntilDone(request: CreateAnnotationRequest) async throws
    -> any GoogleGax.PollableOperation<Annotation>
  {
    try await self.createAnnotationPollingUntilDone(request: request, options: .init())
  }

  public func createAnnotationPollingUntilDone(
    request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Annotation> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Annotation>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAnnotationPollingUntilDone(
    parent: Swift.String,
    annotation: Annotation?,
  ) async throws -> any GoogleGax.PollableOperation<Annotation> {
    let request = CreateAnnotationRequest().with {
      $0.parent = parent
      $0.annotation = annotation
    }
    return try await self.createAnnotationPollingUntilDone(request: request)
  }

  public func getAnnotation(request: GetAnnotationRequest) async throws
    -> GoogleCloudRapidMigrationAssessmentV1.Annotation
  {
    try await self.getAnnotation(request: request, options: .init())
  }

  public func getAnnotation(
    request: GetAnnotationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAnnotation(
    name: Swift.String,
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Annotation {
    let request = GetAnnotationRequest().with {
      $0.name = name
    }
    return try await self.getAnnotation(request: request)
  }

  public func listCollectors(request: ListCollectorsRequest) async throws
    -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse
  {
    try await self.listCollectors(request: request, options: .init())
  }

  public func listCollectors(
    request: ListCollectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCollectorsByItems(
    request: ListCollectorsRequest
  ) -> any AsyncSequence<Collector, Swift.Error> {
    self.listCollectorsByItems(request: request, options: .init())
  }

  /// Lists Collectors in a given project and location.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListCollectors")
  public func listCollectorsByItems(
    request: ListCollectorsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Collector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudRapidMigrationAssessmentV1.ListCollectorsResponse in
      var request = request
      request.pageToken = token
      return try await self.listCollectors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCollectorsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Collector, Swift.Error> {
    let request = ListCollectorsRequest().with {
      $0.parent = parent
    }
    return self.listCollectorsByItems(request: request)
  }

  public func getCollector(request: GetCollectorRequest) async throws
    -> GoogleCloudRapidMigrationAssessmentV1.Collector
  {
    try await self.getCollector(request: request, options: .init())
  }

  public func getCollector(
    request: GetCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCollector(
    name: Swift.String,
  ) async throws -> GoogleCloudRapidMigrationAssessmentV1.Collector {
    let request = GetCollectorRequest().with {
      $0.name = name
    }
    return try await self.getCollector(request: request)
  }

  public func updateCollector(request: UpdateCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCollector(request: request, options: .init())
  }

  public func updateCollector(
    request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateCollectorPollingUntilDone(request: UpdateCollectorRequest) async throws
    -> any GoogleGax.PollableOperation<Collector>
  {
    try await self.updateCollectorPollingUntilDone(request: request, options: .init())
  }

  public func updateCollectorPollingUntilDone(
    request: UpdateCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCollectorPollingUntilDone(
    collector: Collector?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let request = UpdateCollectorRequest().with {
      $0.collector = collector
      $0.updateMask = updateMask
    }
    return try await self.updateCollectorPollingUntilDone(request: request)
  }

  public func deleteCollector(request: DeleteCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCollector(request: request, options: .init())
  }

  public func deleteCollector(
    request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteCollectorPollingUntilDone(request: DeleteCollectorRequest) async throws
    -> any GoogleGax.PollableOperation<Collector>
  {
    try await self.deleteCollectorPollingUntilDone(request: request, options: .init())
  }

  public func deleteCollectorPollingUntilDone(
    request: DeleteCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCollectorPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let request = DeleteCollectorRequest().with {
      $0.name = name
    }
    return try await self.deleteCollectorPollingUntilDone(request: request)
  }

  public func resumeCollector(request: ResumeCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.resumeCollector(request: request, options: .init())
  }

  public func resumeCollector(
    request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resumeCollectorPollingUntilDone(request: ResumeCollectorRequest) async throws
    -> any GoogleGax.PollableOperation<Collector>
  {
    try await self.resumeCollectorPollingUntilDone(request: request, options: .init())
  }

  public func resumeCollectorPollingUntilDone(
    request: ResumeCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func resumeCollectorPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let request = ResumeCollectorRequest().with {
      $0.name = name
    }
    return try await self.resumeCollectorPollingUntilDone(request: request)
  }

  public func registerCollector(request: RegisterCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.registerCollector(request: request, options: .init())
  }

  public func registerCollector(
    request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func registerCollectorPollingUntilDone(request: RegisterCollectorRequest) async throws
    -> any GoogleGax.PollableOperation<Collector>
  {
    try await self.registerCollectorPollingUntilDone(request: request, options: .init())
  }

  public func registerCollectorPollingUntilDone(
    request: RegisterCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func registerCollectorPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let request = RegisterCollectorRequest().with {
      $0.name = name
    }
    return try await self.registerCollectorPollingUntilDone(request: request)
  }

  public func pauseCollector(request: PauseCollectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.pauseCollector(request: request, options: .init())
  }

  public func pauseCollector(
    request: PauseCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func pauseCollectorPollingUntilDone(request: PauseCollectorRequest) async throws
    -> any GoogleGax.PollableOperation<Collector>
  {
    try await self.pauseCollectorPollingUntilDone(request: request, options: .init())
  }

  public func pauseCollectorPollingUntilDone(
    request: PauseCollectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func pauseCollectorPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Collector> {
    let request = PauseCollectorRequest().with {
      $0.name = name
    }
    return try await self.pauseCollectorPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RapidMigrationAssessment_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
